/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeapplication;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;

/**
 *18285
 * @author raju
 */
public class Regi extends javax.swing.JFrame {

    /**
     * Creates new form Regi
     */
    int privId;
    Statement stmt;
    DatabaseConnect db = new DatabaseConnect();
    Connection conn = db.connect();
    public Regi() {
        initComponents();
    }
    
    public Regi(int no, String name, int p) {
        initComponents();
        this.id = no;
        this.uName = name;
        this.privId = p;
    }
    
    public int id;
    public String uName;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jreg1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jpassword2 = new javax.swing.JPasswordField();
        submit1 = new javax.swing.JButton();
        reset1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        jpassword3 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jreg = new javax.swing.JLabel();
        fname1 = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jdate = new com.toedter.calendar.JDateChooser();
        sname1 = new javax.swing.JLabel();
        jlname = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        address1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaddress = new javax.swing.JTextArea();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(255, 153, 102));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jreg1.setBackground(new java.awt.Color(153, 255, 255));
        jreg1.setFont(new java.awt.Font("Times", 1, 48)); // NOI18N
        jreg1.setForeground(new java.awt.Color(102, 102, 255));
        jreg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jreg1.setText("Registration");
        jreg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jFrame1.getContentPane().add(jreg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel7.setText("Username");
        jFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel8.setText("DOB");
        jFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel9.setText("jLabel3");
        jFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jLabel10.setText("jLabel4");
        jFrame1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        jTextField4.setText("jTextField1");
        jFrame1.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        jTextField7.setText("jTextField1");
        jFrame1.getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));
        jFrame1.getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, -1));

        jTextField9.setText("jTextField1");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, -1));

        jTextField10.setText("jTextField1");
        jFrame1.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel11.setText("Password");
        jLabel11.setToolTipText("");
        jFrame1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, -1));

        jpassword2.setPreferredSize(new java.awt.Dimension(175, 36));
        jFrame1.getContentPane().add(jpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 20));

        submit1.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        submit1.setText("Submit");
        submit1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 12, true));
        submit1.setPreferredSize(new java.awt.Dimension(97, 39));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 309, 90, 30));

        reset1.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        reset1.setText("reset");
        reset1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 12));
        reset1.setPreferredSize(new java.awt.Dimension(97, 39));
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 309, 90, 30));

        exit1.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        exit1.setText("exit");
        exit1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 12));
        exit1.setPreferredSize(new java.awt.Dimension(97, 39));
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 50, 40));

        jpassword3.setPreferredSize(new java.awt.Dimension(175, 36));
        jFrame1.getContentPane().add(jpassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 20));

        jLabel12.setText("Retype Password");
        jLabel12.setToolTipText("");
        jFrame1.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jreg.setBackground(new java.awt.Color(153, 255, 255));
        jreg.setFont(new java.awt.Font("Times", 1, 48)); // NOI18N
        jreg.setForeground(new java.awt.Color(102, 102, 255));
        jreg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jreg.setText("Registration");
        getContentPane().add(jreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        fname1.setText("First Name");
        getContentPane().add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        dob.setText("DOB");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, -1));

        password.setText("Password");
        password.setToolTipText("");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, -1));

        jpassword.setPreferredSize(new java.awt.Dimension(175, 36));
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 20));

        submit.setBackground(new java.awt.Color(153, 102, 255));
        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(51, 0, 51));
        submit.setText("Submit");
        submit.setPreferredSize(new java.awt.Dimension(97, 39));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 90, 30));

        reset.setBackground(new java.awt.Color(102, 102, 255));
        reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(51, 0, 51));
        reset.setText("Reset");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reset.setPreferredSize(new java.awt.Dimension(97, 39));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 90, 30));

        exit.setBackground(new java.awt.Color(153, 102, 255));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(51, 0, 51));
        exit.setText("Cancel");
        exit.setPreferredSize(new java.awt.Dimension(97, 39));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 90, 30));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 250, -1));

        sname1.setText("Surname");
        getContentPane().add(sname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlnameActionPerformed(evt);
            }
        });
        getContentPane().add(jlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, -1));

        email.setText("Email ");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        getContentPane().add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, -1));

        address1.setText("Address");
        getContentPane().add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jaddress.setColumns(20);
        jaddress.setRows(5);
        jScrollPane1.setViewportView(jaddress);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String name  = jname.getText();
        String lname  = jlname.getText();
        String password = jpassword.getText();
        String email = jemail.getText();
        String DOB = new SimpleDateFormat("yyyy-MM-dd").format(jdate.getDate());
        String Address = jaddress.getText();
              
        if (fname1.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please complete the fields");
        }
        else
        {
            
        try {
            String sql;  
            sql = "INSERT INTO user(name,lname, password, privilegeID, branchId, dob, address, email) VALUES('" + name +  "' , '" + lname +  "', '" + password + "', '" + privId +  "', 1, '" + DOB +  "' , '" + Address +  "','" + email +  "')" ;
            System.out.println(sql);
            stmt = conn.createStatement();
            stmt.executeUpdate(sql);
            sql = "SELECT id FROM user WHERE name='" + name +  "' AND password='" + password + "' ORDER BY id DESC" ;
            //System.out.println(sql);
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()) {
                int count = rs.getInt("id");
                System.out.println("The new user ID is: " + count);
                JOptionPane.showMessageDialog(null, "Registration complete. Your New Registrator is: "+ count);
            }
            }
        catch(SQLException se){
        //Handle errors for JDBC
        se.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error Occured");
        
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }
        }
        
        this.dispose();
        new Admin(id,uName).setVisible(true);

    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        jname.setText(null);
        jpassword.setText(null);
        jlname.setText(null);
        jemail.setText(null);
        jdate.setDate(null);
        jaddress.setText(null);
        
        

    }//GEN-LAST:event_resetActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exit1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Admin(id, uName).setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void jlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlnameActionPerformed

    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address1;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel fname1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea jaddress;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jlname;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JPasswordField jpassword2;
    private javax.swing.JPasswordField jpassword3;
    private javax.swing.JLabel jreg;
    private javax.swing.JLabel jreg1;
    private javax.swing.JLabel password;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JLabel sname1;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
